#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

# APT Cookbook: used to do apt-get update before running other cookbooks
cookbook 'apt', git: 'https://github.com/opscode-cookbooks/apt'

cookbook 'graphite'
cookbook 'statsd'
